"""Risk Explorer — the synthetic book. Illustrates §3.2 (anti-selection) and §5.5."""
from __future__ import annotations
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import numpy as np
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import streamlit as st

from shared import page_setup, inr, crore, section_ref, riders, trips, claims
from engine.config import CFG
from engine import pricing

page_setup("Risk Explorer")

st.title("Risk Explorer")
st.caption("A synthetic book of 5,000 riders. Illustrates §3.2 (the exposure "
           "problem flat pricing cannot solve) and §5.5 (anti-selection controls).")

st.warning(
    "**This data is synthetic.** There is no public gig-worker telematics "
    "dataset. Riders are generated by `engine/data_gen.py` with a fixed seed, "
    "drawn to match the distributions in the plan: about a quarter ride more "
    "than eight hours a day, about a third work purely in free time, and claim "
    "frequencies come from the §6.1 burning cost table. The generator is "
    "deliberately visible so the assumptions can be challenged."
)

R = riders()
T = trips()
C = claims()

c1, c2, c3, c4 = st.columns(4)
c1.metric("Riders in book", f"{len(R):,}")
c2.metric("Mean safety score", f"{R['safety_score'].mean():.0f}")
c3.metric("Mean hours / month", f"{R['hours_per_month'].mean():.0f}")
c4.metric("Riders with a claim", f"{C['rider_id'].nunique():,}"
          if len(C) else "0")

st.divider()

# ------------------------------------------------------------------ exposure
st.subheader("Exposure is not evenly distributed")
section_ref("§3.2")

l, r = st.columns([3, 2])
with l:
    fig = px.histogram(R, x="hours_per_month", color="segment", nbins=40,
                       color_discrete_sequence=["#8c9bb5", "#5b7fa6", "#2c4f6e"],
                       labels={"hours_per_month": "Active hours per month"})
    fig.update_layout(height=380, margin=dict(l=0, r=0, t=20, b=0),
                      legend=dict(orientation="h", y=1.12),
                      yaxis_title="Riders")
    st.plotly_chart(fig, width="stretch")
with r:
    seg = R.groupby("segment").agg(
        Riders=("rider_id", "count"),
        Mean_hours=("hours_per_month", "mean"),
        Mean_earnings=("monthly_net_earnings", "mean"),
    ).reset_index()
    seg["Share"] = (seg["Riders"] / len(R)).map(lambda v: f"{v:.0%}")
    seg["Mean_hours"] = seg["Mean_hours"].map(lambda v: f"{v:.0f}")
    seg["Mean_earnings"] = seg["Mean_earnings"].map(inr)
    seg.columns = ["Segment", "Riders", "Mean hours/mo", "Mean earnings", "Share"]
    st.dataframe(seg, width="stretch", hide_index=True)
    ratio = R["hours_per_month"].quantile(0.9) / R["hours_per_month"].quantile(0.1)
    st.metric("90th vs 10th percentile hours", f"{ratio:.1f}×")
    st.caption("Expected claim cost scales roughly with exposure. A single "
               "annual premium has to be wrong for one end of this distribution "
               "or the other.")

st.divider()

# ------------------------------------------------------------------ anti-selection
st.subheader("What a flat premium does to this book")
section_ref("§3.2")

flat = st.slider("Flat annual premium (₹)", 2000, 9000,
                 CFG["portfolio"]["gwp_per_worker"], 100)

full_time_hours = 208.0
bc_per_rider = 3148.0
R2 = R.copy()
R2["expected_claim_cost"] = bc_per_rider * (R2["hours_per_month"] / full_time_hours)
R2["flat_margin"] = flat - R2["expected_claim_cost"]
R2["profitable_under_flat"] = R2["flat_margin"] > 0
R2["would_buy"] = R2["expected_claim_cost"] * 1.6 > flat  # crude willingness proxy

fig2 = px.scatter(
    R2.sample(min(2000, len(R2)), random_state=1),
    x="hours_per_month", y="expected_claim_cost", color="flat_margin",
    color_continuous_scale="RdYlGn", labels={
        "hours_per_month": "Active hours per month",
        "expected_claim_cost": "Expected claim cost (₹/yr)",
        "flat_margin": "Margin under flat premium"},
)
fig2.add_hline(y=flat, line_dash="dash", line_color="#2d3436",
               annotation_text=f"flat premium ₹{flat:,}")
fig2.update_layout(height=420, margin=dict(l=0, r=0, t=20, b=0))
st.plotly_chart(fig2, width="stretch")

a, b, c = st.columns(3)
loss_makers = (~R2["profitable_under_flat"]).sum()
a.metric("Riders who lose money under a flat premium", f"{loss_makers:,}",
         f"{loss_makers/len(R2):.0%} of book")
overcharged = R2[R2["expected_claim_cost"] < flat * 0.4]
b.metric("Riders overcharged by 2.5× or more", f"{len(overcharged):,}",
         f"{len(overcharged)/len(R2):.0%} of book")
c.metric("Aggregate margin under flat pricing", crore(R2["flat_margin"].sum()))

st.caption(
    "Everything above the dashed line loses money at that flat premium; "
    "everything well below it is being overcharged and, in a market where the "
    "platform already gives something away free, will simply not buy. Exposure "
    "pricing removes both ends of this problem at once."
)

st.divider()

# ------------------------------------------------------------------ heatmap
st.subheader("Where the risk actually sits")
section_ref("§5.1 — exposure multipliers by time and weather")

pivot = T.pivot_table(index="weather", columns="time_band", values="eeu",
                      aggfunc="mean")
band_order = list(CFG["time_of_day"].keys())
pivot = pivot.reindex(columns=[b for b in band_order if b in pivot.columns])

fig3 = px.imshow(pivot, text_auto=".3f", aspect="auto",
                 color_continuous_scale="OrRd",
                 labels=dict(x="Time band", y="Weather", color="Mean EEU per block"))
fig3.update_layout(height=360, margin=dict(l=0, r=0, t=20, b=0))
st.plotly_chart(fig3, width="stretch")

st.info(
    "**This heatmap is also the accumulation risk in §12.1.** In a conventional "
    "book, exposure is spread across time and geography. In a usage-based book "
    "it is maximally concentrated exactly where risk is highest — the top-right "
    "of this grid, 8pm on a rainy Friday, when tens of thousands of riders are "
    "on the road at once, all with cover live and all being charged our highest "
    "multipliers. One severe urban flood could produce a claims spike a naive "
    "frequency model would never predict, which is why catastrophe "
    "excess-of-loss cover is bought from day one."
)

st.divider()

# ------------------------------------------------------------------ safety
l2, r2 = st.columns(2)
with l2:
    st.subheader("Safety score distribution")
    section_ref("§5.2, Layer B")
    fig4 = px.histogram(R, x="safety_score", nbins=40,
                        color_discrete_sequence=["#5b7fa6"],
                        labels={"safety_score": "Rider Safety Score"})
    for edge, lab in [(50, "Below 50 → ×1.50"), (70, "50–69 → ×1.15"),
                      (90, "70–89 → ×0.95")]:
        fig4.add_vline(x=edge, line_dash="dot", line_color="#888",
                       annotation_text=lab, annotation_position="top")
    fig4.update_layout(height=340, margin=dict(l=0, r=0, t=40, b=0),
                       yaxis_title="Riders")
    st.plotly_chart(fig4, width="stretch")

with r2:
    st.subheader("Premium multiplier by band")
    band = R.groupby("safety_band").agg(Riders=("rider_id", "count")).reset_index()
    band["Multiplier"] = band["safety_band"].map(CFG["safety_score_bands"])
    band["Share"] = (band["Riders"] / len(R)).map(lambda v: f"{v:.0%}")
    order = ["90-100", "70-89", "50-69", "Below 50"]
    band["_o"] = band["safety_band"].map({b: i for i, b in enumerate(order)})
    band = band.sort_values("_o").drop(columns="_o")
    band.columns = ["Band", "Riders", "Multiplier", "Share"]
    st.dataframe(band, width="stretch", hide_index=True)
    st.caption(
        "The score is shown to workers for three months before it affects price "
        "(§5.6, step 4), so they trust it. It both prices behaviour and changes "
        "it — a rider can see exactly which input is costing them and what to fix."
    )

st.divider()

# ------------------------------------------------------------------ claims
if len(C):
    st.subheader("Simulated claims experience")
    section_ref("§6.1 frequencies, scaled by exposure and safety band")
    agg = C.groupby("head").agg(Claims=("count", "sum"),
                                Amount=("amount", "sum")).reset_index()
    agg["Amount"] = agg["Amount"].map(inr)
    agg.columns = ["Benefit head", "Claims", "Total paid"]
    st.dataframe(agg, width="stretch", hide_index=True)
    st.caption("A rider working twice the hours has roughly twice the claim "
               "frequency, and riskier riders claim more often — which is the "
               "whole argument for pricing on measured exposure and behaviour "
               "rather than on the calendar.")

with st.expander("Download the synthetic data"):
    st.download_button("riders.csv", R.to_csv(index=False),
                       "synthetic_riders.csv", "text/csv")
    st.download_button("trips.csv", T.to_csv(index=False),
                       "synthetic_trips.csv", "text/csv")
    if len(C):
        st.download_button("claims.csv", C.to_csv(index=False),
                           "synthetic_claims.csv", "text/csv")
